
target 'Atomik' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'AtomikCommon', :path => '../atomik/'
pod 'SwiftLint'

  target 'AtomikTests' do
    inherit! :search_paths
  end

end