
target 'AtomikSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'common', :path => '../common/'
pod 'SwiftLint'

  target 'AtomikSampleTests' do
    inherit! :search_paths
  end

  target 'AtomikSampleUITests' do
  end

end