name: Build

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    name: Building everything
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '15'
          distribution: 'temurin'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew build

      - name: Api Check
        run: ./gradlew apiCheck